(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["default~LazyComponents-non-credential-non-credential-module~LazyComponents-practionar-data-practiona~bc30a37e"],{

/***/ "./src/app/raw/providerdata.ts":
/*!*************************************!*\
  !*** ./src/app/raw/providerdata.ts ***!
  \*************************************/
/*! exports provided: ProviderCategory, ProviderType, PrimarySpeciality, ProviderAddressCountry, ProviderProfSuffix, ProviderSuffix, ProviderGender, ProviderCitizenship, ProviderContractType, CarrierLocality, ProviderAccount, ProviderPaymentType, ProviderOrganizationType, ProviderLetterMode, ProviderPracticeType, ProviderContractTemplate */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderCategory", function() { return ProviderCategory; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderType", function() { return ProviderType; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PrimarySpeciality", function() { return PrimarySpeciality; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderAddressCountry", function() { return ProviderAddressCountry; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderProfSuffix", function() { return ProviderProfSuffix; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderSuffix", function() { return ProviderSuffix; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderGender", function() { return ProviderGender; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderCitizenship", function() { return ProviderCitizenship; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderContractType", function() { return ProviderContractType; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "CarrierLocality", function() { return CarrierLocality; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderAccount", function() { return ProviderAccount; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderPaymentType", function() { return ProviderPaymentType; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderOrganizationType", function() { return ProviderOrganizationType; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderLetterMode", function() { return ProviderLetterMode; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderPracticeType", function() { return ProviderPracticeType; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProviderContractTemplate", function() { return ProviderContractTemplate; });
const ProviderCategory = [
    'ANC - ANCILLARY PROVIDER',
    'AUD - AUDIOLOGIST',
    'CHO - UNLICENSED PSYCHOLOGIST',
    'CNM - CNM',
    'CNM - CERTIFIED NURSE MIDWIFE',
    'CRNA - CRNA',
    'CRNP - CRNP',
    'CSW - CSW',
    'DC - CIROPRACTORS',
    'DDS - DDS',
    'DNP - DNP',
    'DO - OSTEOPATHIC PHYSICIAN',
    'DO - DOCTOR OF OSTEOPATHIC MEDICINE',
    'DPM - DPM',
    'DPM - DOCTOR OF PODIATRIC MEDICINE',
    'EX - EXTENDER',
    'FM - FAMILY MEDICINE',
    'FNP - FAMILY NURSE PRACTICEONOR',
    'FP - FAMILY PRACTICE',
    'GS - GENERAL SURGERY',
    'HBS - HOSPITAL BASED SPECIALIST',
    'HDO - HEALTH DELIVERY ORGANIZATION',
    'HH - HOME HEALTH PROVIDER',
    'HSP - HOSPITAL',
    'HSP - HOSPITALIST',
    'LCS - LCS',
    'LM - LICENCE MIDWIFE',
    'MD - MD',
    'MD - MD',
    'MID - MID WIFE',
    'MSW - MSW',
    'ND - NATUROPATHIC DOCTOR',
    'NMW - NURSE MIDWIFE',
    'NNP - NNP',
    'NP - NURSE PRACTIONER',
    'NP - NP',
    'OD - OD',
    'ORS - ORAL SURGEON',
    'OT - OT',
    'PA - PA',
    'PA - PHYSICIAN ASSISTANT',
    'PHD - PHO',
    'PHY - PHYSICIAN/MPD',
    'PSY - PSY',
    'RD - RD',
    'RDN - RDN',
    'RN - RN',
    'RNP - RNP',
    'SNF - SKILLED NURCE FACILITY',
    'U - UNSPECIFIED',
    'UNKNOWN - UNKNOWN'
];
const ProviderType = [
    'AIDS Waiver',
    'Allied Health & other programs',
    'AMBULATORY SURGICAL CENTER',
    'AMBULATORY SERVICE PROVIDER',
    'ANESTHESIA SERVICE PROVIDER',
    'COMMUNITY CLINIC',
    'DURABLE MEDICAL EQUIPMENT',
    'Education Agency - Local',
    'EMERGENCE SERVICES PROVIDER',
    'Expanded Access to PC Program',
    'FACILITY',
    'HOME HEALTH SERVICES PROVIDER',
    'HOSPICE CARE',
    'HOSPITAL BASED SPECIALIST',
    'INFECTIONS DIEASE SVCSPROV',
    'LABORATORY SERVICES PROVIDER',
    'ORTHOPEDIC SPECIALTIES',
    'OTHER',
    'PHARMACY SERVICES PROVIDER',
    'PHYSICIAN EXTENDER',
    'PRIMARY CARE PHYSICIAN',
    'PROSTHETIC/ORTHOTIC SUPPLIER',
    'RADIOLOGY SERVICES PROVIDER',
    'REHAB CENTER',
    'SKILLED NURSING FACILITY',
    'SPECIALIST SERVICESS PROVIDER',
    'URGENT CARE SERVICES PROVIDER',
    'WOUND HEALING CENTER'
];
const PrimarySpeciality = [{ abbrevation: 'A', name: 'Allergy' },
    { abbrevation: 'ABS', name: 'ABDOMINAL SURGERY' },
    { abbrevation: 'ACA', name: 'Adult Cardiothoracic Anesthesiology' },
    { abbrevation: 'ACU', name: 'ACUPUNCTURIST' },
    { abbrevation: 'ADL', name: 'Adolescent Medicine Pediatrics' },
    { abbrevation: 'ADM', name: 'Addiction Medicine' },
    { abbrevation: 'ADP', name: 'Addiction Psychiatry' },
    { abbrevation: 'AHF', name: 'ADVANCED HEAR FAILURE AND TRANSPLANT CADIOLOGY' },
    { abbrevation: 'AT', name: 'Allergy/Immunology' },
    { abbrevation: 'ALI', name: 'Clinical Lab Immunology' },
    { abbrevation: 'AM', name: 'Aerospace Medicine' },
    { abbrevation: 'AMB', name: 'AMBULANCE' },
    { abbrevation: 'AMF', name: 'Adolecent Medicine Family/General Practice' },
    { abbrevation: 'AMI', name: 'Adolescent Medicine' },
    { abbrevation: 'AN', name: 'Anesthesiology' },
    { abbrevation: 'ANC', name: 'ANCILLARY PRVIDER' },
    { abbrevation: 'APA', name: 'ALLEREGYPEDIATIC & ADULTS' },
    { abbrevation: 'APM', name: 'Anesthesiology/Pain Management' },
    { abbrevation: 'APT', name: 'AQUATIC PHYSICAL THERAPY' },
    { abbrevation: 'APY', name: 'ADDICTION PHYSCHIATRY' },
    { abbrevation: 'AR', name: 'Abdominal Radiology' },
    { abbrevation: 'AS', name: 'Abodominal Surgery' },
    { abbrevation: 'ASC', name: 'AMBULATORY SURGICAL CENTER' },
    { abbrevation: 'ASO', name: 'Advance Surgica Oncology' },
    { abbrevation: 'ATP', name: 'Anatomic Pathology' },
    { abbrevation: 'AUD', name: 'AUDIOLOGY' },
    { abbrevation: 'BBK', name: 'Bloodbanking/Transfusion Medicare' },
    { abbrevation: 'BE', name: 'BRONCHO - ESOPHAGOLOGY' },
    { abbrevation: 'BHS', name: 'BEHAVIORAL SCIENCES' },
    { abbrevation: 'BLB', name: 'BLOOD BANKING' },
    { abbrevation: 'BMT', name: 'BONEMARROW TRANSPLANT' },
    { abbrevation: 'BRS', name: 'BREAST SURGERY' },
    { abbrevation: 'C', name: 'CARDIOLOGY' },
    { abbrevation: 'CAP', name: 'Chlid Abuse Pediatrics' },
    { abbrevation: 'CAR', name: 'CARDIAC REHABITATION' },
    { abbrevation: 'CBG', name: 'Clinical Cytogenics' },
    { abbrevation: 'CCM', name: 'Critical Care Medicine-IM' },
    { abbrevation: 'CCP', name: 'Pediatric Critical Care Medicine' },
    { abbrevation: 'CCS', name: 'Surgical Critical Care' },
    { abbrevation: 'CD', name: 'Cardiovascular Diseas' },
    { abbrevation: 'CDS', name: 'CARDIOVASCULAR SURGERY' },
    { abbrevation: 'CDT', name: 'CARDIO THORACTIC' },
    { abbrevation: 'CFS', name: 'Carniofacial Surgery' },
    { abbrevation: 'CG', name: 'Clinical Genetics' },
    { abbrevation: 'CHN', name: 'Child Neurology' },
    { abbrevation: 'CHP', name: 'Child & Adolescent Psychiatry' },
    { abbrevation: 'CHR', name: 'CHIROPRACTIC' },
    { abbrevation: 'CHS', name: 'Congenital Cardiac Surgery ( Thoracic Surgery )' },
    { abbrevation: 'CLC', name: 'CLINIC CENTER' },
    { abbrevation: 'CLP', name: 'Clinical Pathology' },
    { abbrevation: 'CM', name: 'CASE MANAGER' },
    { abbrevation: 'CMG', name: 'Clinical Molecular Genetics' },
    { abbrevation: 'CN', name: 'Clinical Neurophysiology' },
    { abbrevation: 'CNM', name: 'Certified Nurse Midwife' },
    { abbrevation: 'CNP', name: 'CLINICAL NEUROPHYSIOLOGY' },
    { abbrevation: 'CP', name: 'CARDIOLOGY  PEDRIATIC' },
    { abbrevation: 'CPO', name: 'CRTFIED PROSTHETIST ORTHOTIST' },
    { abbrevation: 'CRS', name: 'Colon & Rectal Surgery' },
    { abbrevation: 'CS', name: 'Cosmetic Surgery' },
    { abbrevation: 'CTC', name: 'CRITICAL CARE' },
    { abbrevation: 'CTR', name: 'Cardiothoracic Radiology' },
    { abbrevation: 'D', name: 'Dermatology' },
    { abbrevation: 'DBP', name: 'Developmental - Behavioral Pediatri' },
    { abbrevation: 'DC', name: 'DIAGNOSTIC CENTER' },
    { abbrevation: 'DD', name: 'DENTIST' },
    { abbrevation: 'DDL', name: 'Dermatology Immunology / Diagnos Lab' },
    { abbrevation: 'DIA', name: 'Diabetes & Metabolism' },
    { abbrevation: 'DLS', name: 'END - STAGE RENAL DISEASE ( ESRD )' },
    { abbrevation: 'DME', name: 'DURABLE MEDICAL EQUIPMENT' },
    { abbrevation: 'DMP', name: 'Dermatopathology' },
    { abbrevation: 'DR', name: 'Diagnostic Radiology' },
    { abbrevation: 'DS', name: 'DIAGNOSTIC RADIOLOGY' },
    { abbrevation: 'EDM', name: 'ELECTRODIAGNOSTIC MED' },
    { abbrevation: 'ELE', name: 'ELECTROPHYSIOLOGIST' },
    { abbrevation: 'EM', name: 'Emergency Medicine' },
    { abbrevation: 'EN', name: 'ENDOCRINOLOGY' },
    { abbrevation: 'END', name: 'Endocrinology' },
    { abbrevation: 'ENP', name: 'ENDOCRINOLOGY  PEDRIATIC' },
    { abbrevation: 'EP', name: 'Epidemiology' },
    { abbrevation: 'ES', name: 'ENDOCRINE SURGERY' },
    { abbrevation: 'ESM', name: 'Emergency / Sports Medicine' },
    { abbrevation: 'ESN', name: 'Endovascular Surgical Neuroradiology' },
    { abbrevation: 'EST', name: 'ESTHETICIAN' },
    { abbrevation: 'ETX', name: 'Medical Toxicology - Emergency Medicine' },
    { abbrevation: 'ENA', name: '** DO NOT USE FAMILY NURSE PRACTITIONER' },
    { abbrevation: 'FNP', name: 'FAMILY NURSE PRACTITIONER' },
    { abbrevation: 'FOP', name: 'Forensic Pathology' },
    { abbrevation: 'FP', name: 'Family Practice Geriatric Medicine - FP' },
    { abbrevation: 'FPL', name: 'FAMILY PLANNING' },
    { abbrevation: 'FPS', name: 'Facial Plastic Surgery' },
    { abbrevation: 'FSM', name: 'Sports Medicine - FP' },
    { abbrevation: 'G', name: 'GYNECOLOGY' },
    { abbrevation: 'GC', name: 'GENETICS CENTERS' },
    { abbrevation: 'GE', name: 'Gastroenterology' },
    { abbrevation: 'GER', name: 'GERIATRIC MEDICINE' },
    { abbrevation: 'GO', name: 'Gynecological Oncology' },
    { abbrevation: 'GP', name: 'General Practice' },
    { abbrevation: 'GPM', name: 'General Preventive Medicine' },
    { abbrevation: 'GS', name: 'General Surgery' },
    { abbrevation: 'GYN', name: 'Gynecology' },
    { abbrevation: 'GYO', name: 'GYNECOLOGY / ONCOLOGY' },
    { abbrevation: 'H', name: 'HEMATOLOGY' },
    { abbrevation: 'HBS', name: 'HEPATOBILIARY SURGERY' },
    { abbrevation: 'HC', name: 'HOSPICE CARE' },
    { abbrevation: 'HDO', name: 'HEALTH DELIVERY ORGANIZATION' },
    { abbrevation: 'HE', name: 'HEPATOLOGY' },
    { abbrevation: 'HEM', name: 'Hematology - IM' },
    { abbrevation: 'HEP', name: 'Hepatology' },
    { abbrevation: 'HHA', name: 'HOME HEALTH AGENCY' },
    { abbrevation: 'HIS', name: 'HEARING INSTRUMENT SPECIALIST' },
    { abbrevation: 'HIV', name: 'HIV MEDICINE' },
    { abbrevation: 'HMP', name: 'Hematology - Pathology' },
    { abbrevation: 'HNS', name: 'Head & Neck Surgery' },
    { abbrevation: 'HO', name: 'Hematology / Oncology' },
    { abbrevation: 'HOP', name: 'HEM / ONC  PEDIATRIC' },
    { abbrevation: 'HOS', name: 'Hospitalist' },
    { abbrevation: 'HPA', name: 'Hospice & Palliative Medicine ( Anesthesiology )' },
    { abbrevation: 'HPD', name: 'Hospice & Palliative Medicine ( Radiology )' },
    { abbrevation: 'HPE', name: 'Hospice & Palliative Medicine ( Emergency Medicine )' },
    { abbrevation: 'HPF', name: 'Hospice & Palliative Medicine ( Family Medicine )' },
    { abbrevation: 'HPI', name: 'Hospice & Palliative Medicine ( Internal Medicine )' },
    { abbrevation: 'HPL', name: 'HOSPITALIST' },
    { abbrevation: 'HPM', name: 'Hospice & Palliative Medicine' },
    { abbrevation: 'HPN', name: 'Hospice & Palliative Medicine ( Psych & Neurology )' },
    { abbrevation: 'HPO', name: 'Hospice & Palliative Medicine ( Obstetrics & Gynecology )' },
    { abbrevation: 'HPP', name: 'Hospice & Palliative Medicine ( Pediatrics )' },
    { abbrevation: 'HPR', name: 'Hospice & Palliative Medicine ( Physical Med & Rehab )' },
    { abbrevation: 'HRP', name: 'HIGH RISK PREGNANCY' },
    { abbrevation: 'HS', name: 'Hand Surgery' },
    { abbrevation: 'HSO', name: 'Hand Surgery Orthopedic Surgery' },
    { abbrevation: 'HSP', name: 'Hospital' },
    { abbrevation: 'IC', name: 'Interventional Cardiology' },
    { abbrevation: 'ICE', name: 'Cardiac Electrophysiology' },
    { abbrevation: 'HPO', name: 'Hospice & Palliative Medicine ( Obstetrics & Gynecology )' },
    { abbrevation: 'HPP', name: 'Hospice & Palliative Medicine ( Pediatrics )' },
    { abbrevation: 'HPR', name: 'Hospice & Palliative Medicine ( Physical Med & Rehab )' },
    { abbrevation: 'HRP', name: 'HIGH RISK PREGNANCY' },
    { abbrevation: 'HS', name: 'Hand Surgery' },
    { abbrevation: 'HSO', name: 'Hand Surgery Orthopedic Surgery' },
    { abbrevation: 'HSP', name: 'Hospital' },
    { abbrevation: 'IC', name: 'Interventional Cardiology' },
    { abbrevation: 'ICE', name: 'Cardiac Electrophysiology' },
    { abbrevation: 'ID', name: 'Infectious Disease' },
    { abbrevation: 'IDP', name: 'INFECTIOUS DIS  PEDIATRIC' },
    { abbrevation: 'IG', name: 'Immunology' },
    { abbrevation: 'ILI', name: 'Clinical / Laboratory Immunology' },
    { abbrevation: 'IM', name: 'Internal Medicine' },
    { abbrevation: 'IMG', name: 'Geriatric Medicine - IM' },
    { abbrevation: 'IMM', name: 'IMMUNOLOGY' },
    { abbrevation: 'INC', name: 'INFUSSION CENTER' },
    { abbrevation: 'IP', name: 'INPATIENT PSYCHIATRIC' },
    { abbrevation: 'IPM', name: 'Interventional Pain Medicine' },
    { abbrevation: 'ISM', name: 'Sports Medicine - IM' },
    { abbrevation: 'LAB', name: 'CLINICAL LABORATORY' },
    { abbrevation: 'LCS', name: 'CLINICAL SOCIAL WORKER' },
    { abbrevation: 'LM', name: 'Legal Medicine' },
    { abbrevation: 'MBG', name: 'Medical Biochemical Genetics' },
    { abbrevation: 'MDM', name: 'Medical Management' },
    { abbrevation: 'MFC', name: 'MARRIAGE / FAMILY COUNSELOR' },
    { abbrevation: 'MFM', name: 'Maternal & Fetal Medicine' },
    { abbrevation: 'MES', name: 'MAXILLOFACIAL SURGERY' },
    { abbrevation: 'MG', name: 'Medical Genetics' },
    { abbrevation: 'MGG', name: 'Molecular Genetic Pathology Medical Genetics' },
    { abbrevation: 'MGP', name: 'Molecular Genetic Pathology' },
    { abbrevation: 'MM', name: 'Medical Microbiology' },
    { abbrevation: 'MPD', name: 'Internal Medicine - Pediatrics' },
    { abbrevation: 'MS', name: 'MULTI - SPECIALTY GROUP' },
    { abbrevation: 'MSR', name: 'Musculoskeletal Radiology' },
    { abbrevation: 'MT', name: 'MEDICAL TRANSPORTATION' },
    { abbrevation: 'N', name: 'Neurology' },
    { abbrevation: 'N/A', name: 'CLINICAL LABORATORY' },
    { abbrevation: 'NA', name: 'NEUROPATHOLOGY' },
    { abbrevation: 'NC', name: 'Nuclear Cardiology' },
    { abbrevation: 'NDN', name: 'Neurodevelopmental Disabilities Neurology' },
    { abbrevation: 'NDP', name: 'Neurodevelopmental Disabilities Pediatrics' },
    { abbrevation: 'NE', name: 'NEPHROLOGY' },
    { abbrevation: 'NEP', name: 'Nephrology' },
    { abbrevation: 'NM', name: 'Nuclear Medicine' },
    { abbrevation: 'NMF', name: 'NURSE MIDWIFE FURNISHER' },
    { abbrevation: 'NMN', name: 'Neuromuscular Medicine' },
    { abbrevation: 'NMP', name: 'Neuromuscular Medicine ( Physical Med & Rehab )' },
    { abbrevation: 'NO', name: 'Otology / Neurotology' },
    { abbrevation: 'NOP', name: 'NEURO - OPHTHALMOLOGY' },
    { abbrevation: 'NP', name: 'Neuropathology' },
    { abbrevation: 'NPM', name: 'Neonatal - Perinatal Medicine' },
    { abbrevation: 'NR', name: 'Nuclear Radiology' },
    { abbrevation: 'NRA', name: 'NEURORADIOLOGY' },
    { abbrevation: 'NRN', name: 'Neurology / Diag Rad / Neuroradiology' },
    { abbrevation: 'NS', name: 'Neurological Surgery' },
    { abbrevation: 'NSP', name: 'Pediatric Surgery - Neurological' },
    { abbrevation: 'NTR', name: 'Nutrition' },
    { abbrevation: 'NU.', name: 'NEUROLOGY' },
    { abbrevation: 'NUE', name: 'NEUROLOGY  EPILEPTOLOGY' },
    { abbrevation: 'NUO', name: 'NEURO - ONCOLOGY' },
    { abbrevation: 'NUP', name: 'Neuropsychiatry' },
    { abbrevation: 'O', name: 'ONCOLOGY' },
    { abbrevation: 'OAR', name: 'Adult Reconstructive Orthopedics' },
    { abbrevation: 'OBG', name: 'Obstetrics & Gynecology' },
    { abbrevation: 'OBS', name: 'Obstetrics' },
    { abbrevation: 'OCC', name: 'Obstetric Critical Care Medicine' },
    { abbrevation: 'OCT', name: 'OCCUPATIONAL THERAPY' },
    { abbrevation: 'OCU', name: 'OCULARIST - TECHNICIAN / TECH' },
    { abbrevation: 'OFA', name: 'Foot & Ankle Orthopedics' },
    { abbrevation: 'OFS', name: 'Oral & Maxillofacial Surgery' },
    { abbrevation: 'OM', name: 'Occupational Medicine' },
    { abbrevation: 'OMF', name: 'Maxillofacial and Oral Surgery' },
    { abbrevation: 'OMM', name: 'Osteopathic Manipulative Medicin' },
    { abbrevation: 'OMO', name: 'Musculoskeletal Oncology' },
    { abbrevation: 'ON', name: 'Medical Oncology' },
    { abbrevation: 'ONH', name: 'ONCOLOGY / HEMATOLOGY' },
    { abbrevation: 'OP', name: 'Pediatric Orthopedics' },
    { abbrevation: 'OPC', name: 'OPTICIAN' },
    { abbrevation: 'OPG', name: 'OPHTHALMOLOGY  GLAUCOMA' },
    { abbrevation: 'OPH', name: 'Ophthalmology' },
    { abbrevation: 'OPP', name: 'OPHTHALMOLOGY  PEDIATRIC' },
    { abbrevation: 'OPR', name: 'OPHTHALMOLOGY  RETINA' },
    { abbrevation: 'OPS', name: 'OCCULAR PLASTIC SURGERY' },
    { abbrevation: 'OPT', name: 'OPTOMETRY' },
    { abbrevation: 'OR', name: 'ORTHOPEDICS' },
    { abbrevation: 'ORO', name: 'ORTHOPEDIC SURGERY  ONCOLOGY' },
    { abbrevation: 'ORP', name: 'ORTHOPEDICS  PEDRIATIC' },
    { abbrevation: 'ORS', name: 'Orthopedic Surgery' },
    { abbrevation: 'ORT', name: 'ORTHOPEDIC' },
    { abbrevation: 'OS', name: 'Other Specialty' },
    { abbrevation: 'OSM', name: 'Sports Medicine - Orthopedics' },
    { abbrevation: 'OSS', name: 'Spine Surgery' },
    { abbrevation: 'OT', name: 'OTORHINOLARYNGOLOGY' },
    { abbrevation: 'OTO', name: 'Otolaryngology' },
    { abbrevation: 'OTP', name: 'OTORHINOLARYNGOLOG PEDIATRIC' },
    { abbrevation: 'OTR', name: 'Orthopedic Trauma Surgey' },
    { abbrevation: 'P', name: 'PEDIATRICS' },
    { abbrevation: 'PA ', name: 'Physician Assistant' },
    { abbrevation: 'PAC', name: 'PHYSICIAN ASSISTANT CE' },
    { abbrevation: 'PAN', name: 'Pediatric Anesthesiology' },
    { abbrevation: 'PAS', name: 'PHYSICIAN ASSISTANT' },
    { abbrevation: 'PAT', name: 'PHYSICIAN ASSISTANT' },
    { abbrevation: 'PCC', name: 'PEDIATRIC CRITICAL CARE' },
    { abbrevation: 'PCH', name: 'Chemical Pathology' },
    { abbrevation: 'PCP', name: 'Cytopathology' },
    { abbrevation: 'PCS', name: 'Pediatric Cardiothoracic Surgery' },
    { abbrevation: 'PD', name: 'Pediatrics' },
    { abbrevation: 'PDA', name: 'Pediatric Allergy' },
    { abbrevation: 'PDC', name: 'Pediatric Cardiology' },
    { abbrevation: 'PDD', name: 'Pediatric Dermatology' },
    { abbrevation: 'PDÉ', name: 'Pediatric Endocrinology' },
    { abbrevation: 'PDI', name: 'Pediatric Infectious Disease' },
    { abbrevation: 'PDO', name: 'Pediatric Otolaryngology' },
    { abbrevation: 'PDP', name: 'Pediatric Pulmonology' },
    { abbrevation: 'PDR', name: 'Pediatric Radiology' },
    { abbrevation: 'PDS', name: 'Pediatric Surgery' },
    { abbrevation: 'PDT', name: 'Pediatric Medical Toxicology' },
    { abbrevation: 'PDU', name: 'PEDIATRIC UROLOGY' },
    { abbrevation: 'PE', name: 'Pediatric Emergency Medicine - EM' },
    { abbrevation: 'PEM', name: 'Pediatric Emergency Medicine - Pediatrics' },
    { abbrevation: 'PER', name: 'PERINATOLOGY' },
    { abbrevation: 'PFP', name: 'Forensic Psychiatry' },
    { abbrevation: 'PG', name: 'Pediatric Gastroenterology' },
    { abbrevation: 'PGI', name: 'PEDIATRIC GASTROENTEROLOGY' },
    { abbrevation: 'PH', name: 'PUBLIC HEALTH' },
    { abbrevation: 'PHA', name: 'PHARMACY' },
    { abbrevation: 'PHM', name: 'Pharmaceutical Medicine' },
    { abbrevation: 'PHO', name: 'Pediatric Hematology / Oncology' },
    { abbrevation: 'PHP', name: 'Public Health & General Preventive Medicine' },
    { abbrevation: 'PIR', name: 'PEDIATRIC INTERVENTIONAL RADIOLOGY' },
    { abbrevation: 'PL', name: 'PHYSIOLOGICAL LABORATORY' },
    { abbrevation: 'PLI', name: 'Pediatric Clinical & Lab Immunology' },
    { abbrevation: 'PLM', name: 'Palliative Medicine' },
    { abbrevation: 'PM', name: 'Physical Medicine & Rehabilitation' },
    { abbrevation: 'PMD', name: 'Pain Medicine' },
    { abbrevation: 'PMM', name: 'Pain Medicine' },
    { abbrevation: 'PMN', name: 'Pain Medicine ( Neurology )' },
    { abbrevation: 'PN', name: 'Pediatric Nephrology' },
    { abbrevation: 'PNM', name: 'PAIN MANAGEMENT' },
    { abbrevation: 'PNP', name: 'PEDIATRIC NEPHROLOGY' },
    { abbrevation: 'PO', name: 'PROSTHETIC / ORTHOTIC' },
    { abbrevation: 'POD', name: 'PODIATRY' },
    { abbrevation: 'PP', name: 'Pediatric Pathology' },
    { abbrevation: 'PPN', name: 'Pain Medicine ( Psychiatry )' },
    { abbrevation: 'PPR', name: 'Pediatric Rheumatology' },
    { abbrevation: 'PR', name: 'PEDIATRIC RHEUMATOLOGY' },
    { abbrevation: 'PRD', name: 'Procedural Dermatology' },
    { abbrevation: 'PRM', name: 'Pediatric Rehabilitation Medicine' },
    { abbrevation: 'PRO', name: 'Proctology' },
    { abbrevation: 'PRS', name: 'PLASTIC AND RECONSTRUCTIVE SUR' },
    { abbrevation: 'PS', name: 'PEDIATRIC SURGERY' },
    { abbrevation: 'PSH', name: 'Plastic Surgery Within Head & Neck' },
    { abbrevation: 'PSI', name: 'Plastic Surgey - Integrated' },
    { abbrevation: 'PSM', name: 'Sports Medicine - Pediatric' },
    { abbrevation: 'PSP', name: 'Plastic Surgey Within Head & Neck' },
    { abbrevation: 'PSY', name: 'PSYCHOLOGY' },
    { abbrevation: 'PT', name: 'PHYSICAL THERAPY' },
    { abbrevation: 'PTH', name: 'Anatomic / Clinical Pathology' },
    { abbrevation: 'PTP', name: 'Pediatrics Transplant Hepatology' },
    { abbrevation: 'PTX', name: 'Medical Toxicology - Preventive Medicine' },
    { abbrevation: 'PU', name: 'PULMONARY DISEASES' },
    { abbrevation: 'PUD', name: 'Pulmonary Disease' },
    { abbrevation: 'PUP', name: 'PULMONARY  PEDIATRIC' },
    { abbrevation: 'PY', name: 'PSYCHIATRY' },
    { abbrevation: 'PYA', name: 'Psychoanalysis' },
    { abbrevation: 'PYC', name: 'PSYCHIATRY  CHILD' },
    { abbrevation: 'PYG', name: 'Geriatric Psychiatry' },
    { abbrevation: 'PYM', name: 'Psychosomatic Medicine' },
    { abbrevation: 'PYN', name: 'PSYCHIATRY & NEUROLOGY NEUROLOGY' },
    { abbrevation: 'R', name: 'Radiology' },
    { abbrevation: 'RD', name: 'REGISTERED DIETITIAN' },
    { abbrevation: 'REB', name: 'RADIOLOGY' },
    { abbrevation: 'ECO', name: 'BIOPSY' },
    { abbrevation: 'REH', name: 'REHAB CENTER' },
    { abbrevation: 'REN', name: 'Reproductive Endocrinology' },
    { abbrevation: 'RF', name: 'RADIOLOGY FACILITY' },
    { abbrevation: 'RHU', name: 'Rheumatology' },
    { abbrevation: 'RN', name: 'RADIOLOGY  NUCLEAR MEDICINE' },
    { abbrevation: 'RNA', name: 'NURSE ANESTHETIST' },
    { abbrevation: 'RNN', name: 'REGISTERED NURSE' },
    { abbrevation: 'RNR', name: 'Neuroradiology' },
    { abbrevation: 'RO', name: 'Radiation Oncology' },
    { abbrevation: 'RON', name: 'RADIATION ONCOLOGY' },
    { abbrevation: 'RP', name: 'Radiological Physics' },
    { abbrevation: 'RPM', name: 'Pediatric Rehab Medicine' },
    { abbrevation: 'RRT', name: 'RADIOLOGY  RADIATION THERAPY' },
    { abbrevation: 'RS', name: 'RECONSTRUCTIVE SURGERY' },
    { abbrevation: 'SCC', name: 'SURGERY  CRITICAL CARE' },
    { abbrevation: 'SCI', name: 'Spinal Cord Injury' },
    { abbrevation: 'SCM', name: 'SUPPORTIVE CARE MEDICINE' },
    { abbrevation: 'SCR', name: 'SURGERY  COLON & RECTAL' },
    { abbrevation: 'SG', name: 'SURGERY  GENERAL' },
    { abbrevation: 'SH', name: 'SURGERY HAND SHN - SURGERY  HEAD & NECK' },
    { abbrevation: 'SHO', name: 'Student in an Organized Health Care Education / Training' },
    { abbrevation: 'SLD', name: 'SLEEP MEDICINE' },
    { abbrevation: 'SM', name: 'Sports Medicine' },
    { abbrevation: 'SMI', name: 'Sleep Medicine ( Internal Medicine )' },
    { abbrevation: 'SMN', name: 'Sleep Medicine ( Psych & Neurology )' },
    { abbrevation: 'SMO', name: 'Sleep Medicine ( Otolaryngology )' },
    { abbrevation: 'SMP', name: 'Sleep Medicine ( Pediatrics )' },
    { abbrevation: 'SN', name: 'SURGERY  NEUROLOGICAL' },
    { abbrevation: 'SNF', name: 'SKILLED NURSING FACILITY' },
    { abbrevation: 'SO', name: 'Surgical Oncology' },
    { abbrevation: 'SON', name: 'SURGERY  ONCOLOGY' },
    { abbrevation: 'SOR', name: 'SURGERY  ORTHOPEDIC' },
    { abbrevation: 'SP', name: 'SPECIALTIES CLINIC' },
    { abbrevation: 'SPC', name: 'SPECIALTIES CLINIC' },
    { abbrevation: 'SPE', name: 'SPECIALIST' },
    { abbrevation: 'SPH', name: 'SPECIAL HOSPITAL' },
    { abbrevation: 'SPR', name: 'SURGERY  PLASTIC & REC' },
    { abbrevation: 'SS', name: 'SPINAL SURGERY' },
    { abbrevation: 'ST', name: 'SPEECH THERAPY' },
    { abbrevation: 'STC', name: 'SURGERY  THORACIC & CARDIOVASC' },
    { abbrevation: 'SU', name: 'SURGERY  UROLOGICAL' },
    { abbrevation: 'SUR', name: 'SURGEON' },
    { abbrevation: 'SV', name: 'SURGERY  VASCULAR' },
    { abbrevation: 'THI', name: 'Transplant Hepatology ( Internal Medicine )' },
    { abbrevation: 'TMJ', name: 'TEMPORAL MANDIBULAR JOINTS D' },
    { abbrevation: 'TRP', name: 'THERAPEUTIC RADIOLOGY' },
    { abbrevation: 'TRS', name: 'Trauma Surgery' },
    { abbrevation: 'TS', name: 'Thoracic Surgery' },
    { abbrevation: 'TSC', name: 'Transplant Cardiology  Ady Heart Falure' },
    { abbrevation: 'TSP', name: 'TRANSPLANT' },
    { abbrevation: 'TTS', name: 'Transplant Surgery' },
    { abbrevation: 'U', name: 'Urology' },
    { abbrevation: 'UC', name: 'URGENT CARE' },
    { abbrevation: 'UCM', name: 'Urgent Care Medicine' },
    { abbrevation: 'UGY', name: 'UROGYNECOLOGY' },
    { abbrevation: 'UM', name: 'Undersea Medicine' },
    { abbrevation: 'UME', name: 'Undersea and Hyperbaric Medicine EM' },
    { abbrevation: 'UP', name: 'Pediatric Urology' },
    { abbrevation: 'UR', name: 'UROLOGY' },
    { abbrevation: 'US', name: 'Unspecified Specialty' },
    { abbrevation: 'USH', name: 'UNDERSEA & HYPERBARIC MEDICINE' },
    { abbrevation: 'VIR', name: 'Vascular / Interventional Radiology' },
    { abbrevation: 'VM', name: 'Vascular Medicine' },
    { abbrevation: 'VN', name: 'Vascular Neurology' },
    { abbrevation: 'VND', name: 'VENDOR' },
    { abbrevation: 'VS', name: 'Vascular Surgery' },
    { abbrevation: 'WC', name: 'WOUND CARE' },
    { abbrevation: 'WM', name: 'WEIGHT MANAGEMENT' }
];
const ProviderAddressCountry = [
    { id: "05000", name: "ALAMEDA" },
    { id: "05010", name: "ALPINE" },
    { id: "05020", name: "AMADOR" },
    { id: "05030", name: "BUTTE" },
    { id: "05040", name: "CALAVERAS" },
    { id: "05050", name: "COLUSA" },
    { id: "05060", name: "CONTRA COSTA" },
    { id: "05070", name: "DEL NORTE" },
    { id: "05080", name: "ELDORADO" },
    { id: "05090", name: "FRESNO" },
    { id: "05100", name: "GLENN" },
    { id: "05110", name: "HUMBOLDT" },
    { id: "05120", name: "IMPERIAL" },
    { id: "05130", name: "INYO" },
    { id: "05140", name: "KERN" },
    { id: "05150", name: "KINGS" },
    { id: "05160", name: "LAKE" },
    { id: "05170", name: "LASSEN" },
    { id: "05200", name: "LOS ANGELES" },
    { id: "05300", name: "MADERA" },
    { id: "05310", name: "MARIN" },
    { id: "05320", name: "MARIPOSA" },
    { id: "05330", name: "MENDOCINO" },
    { id: "05340", name: "MERCED" },
    { id: "05350", name: "MODOC" },
    { id: "05360", name: "MONO" },
    { id: "05370", name: "MONTEREY" },
    { id: "05380", name: "NAPA" },
    { id: "05390", name: "NEVADA" },
    { id: "05400", name: "ORANGE" },
    { id: "05410", name: "PLACER" },
    { id: "05420", name: "PLUMAS" },
    { id: "05430", name: "RIVERSIDE" },
    { id: "05440", name: "SACRAMENTO" },
    { id: "05450", name: "SAN BENITO" },
    { id: "05460", name: "SAN BERNARDINO" },
    { id: "05470", name: "SAN DIEGO" },
    { id: "05480", name: "SAN FRANCISCO" },
    { id: "05490", name: "SAN JOAQUIN" },
    { id: "05500", name: "SAN LUIS OBISPO" },
    { id: "05510", name: "SAN MATEO" },
    { id: "05520", name: "SANTA BARBARA" },
    { id: "05530", name: "SANTA CLARA" },
    { id: "05540", name: "SANTA CRUZ" },
    { id: "05550", name: "SHASTA" },
    { id: "05560", name: "SIERRA" },
    { id: "05570", name: "SISKIYOU" },
    { id: "05580", name: "SOLANO" },
    { id: "05590", name: "SONOMA" },
    { id: "05600", name: "STANISLAUS" },
    { id: "05610", name: "SUTTER" },
    { id: "05620", name: "TEHAMA" },
    { id: "05630", name: "TRINITY" },
    { id: "05640", name: "TULARE" },
    { id: "05650", name: "TUOLUMNE" },
    { id: "05660", name: "VENTURA" },
    { id: "05670", name: "YOLO" },
    { id: "05680", name: "YUBA" }
];
const ProviderProfSuffix = [
    'ACNP',
    'CNM',
    'CRNA',
    'CRNP',
    'CSW',
    'DC',
    'DDM',
    'DDS',
    'DNP',
    'DO',
    'DO, JD',
    'DO, MPH',
    'DO, PHD',
    'DOM REPUB',
    'DPM',
    'EXT',
    'FNP',
    'JD',
    'LCS',
    'LMW',
    'M.D',
    'MBA',
    'MD',
    'MD, JD',
    'MD, MBA',
    'MD, PHD',
    'MD.',
    'MHA',
    'MIDWIFEE',
    'MPH',
    'MPH, PHD',
    'MSW',
    'MW',
    'ND',
    'NMW',
    'NNP',
    'NP',
    'OD',
    'OT',
    'PA',
    'PA-',
    'PA-C',
    'PHD',
    'PHD,JD,MD',
    'PNP',
    'PSY',
    'PT',
    'RD',
    'RDN',
    'RN',
    'RNP',
    'UNKNOWN',
    'VENDOR'
];
const ProviderSuffix = ['II',
    'III',
    'IV',
    'JR.',
    'SR.',
    'V',
    'VI'];
const ProviderGender = [
    'Male',
    'Female',
    'Not Applicable'
];
const ProviderCitizenship = [
    'NOT APPLICABLE',
    'UNKNOWN',
    'YES',
    'NO'
];
const ProviderContractType = ['CONTRACT - NOTCREDENTIALED', 'CONTRACT NO REFERAL', 'CONTRACTED', 'CONTRACTED-CAPITATED', 'LETTER OF AGREEMENT', 'MOU AGREMENT ONLY', 'NON CONTRACTED', 'OTHER', 'PT SPECIFIC LOA'];
const CarrierLocality = [
    { carrier: '14212', locality: '99', name: 'REST OF MASSACHUSETTS' },
    { carrier: '08202', locality: '01', name: 'DETROIT' },
    { carrier: '08202', locality: '99', name: 'REST OF MICHIGAN ' },
    { carrier: '06202', locality: '00', name: 'MINNESOTA' },
    { carrier: '07302', locality: '00', name: 'MISSISSIPPI' },
    { carrier: '05302', locality: '02', name: 'METROPOLITAN KANSAS CITY' },
    { carrier: '05302', locality: '01', name: 'METROPOLITAN ST . LOUIS' },
    { carrier: '05302', locality: '99', name: 'REST OF MISSOURI ' },
    { carrier: '03202', locality: '01', name: 'MONTANA **' },
    { carrier: '05402', locality: '00', name: 'NEBRASKA' },
    { carrier: '01312', locality: '00', name: 'NEVADA **' },
    { carrier: '14312', locality: '40', name: 'NEW HAMPSHIRE' },
    { carrier: '12402', locality: '01', name: 'NORTHERN ND' },
    { carrier: '12402', locality: '99', name: 'REST OF NEW JERSEY' },
    { carrier: '04212', locality: '05', name: 'NEW MEXICO' },
    { carrier: '13202', locality: '01', name: 'MANHATTAN' },
    { carrier: '13202', locality: '02', name: 'NYC SUBURBS // LONG ISLAND ' },
    { carrier: '13202', locality: '03', name: 'POUGHKPSIE // N NYC SUBURBS' },
    { carrier: '13292', locality: '04', name: 'QUEENS' },
    { carrier: '13282', locality: '99', name: 'REST OF NEW YORK' },
    { carrier: '11502', locality: '00', name: 'NORTH CAROLINA' },
    { carrier: '03302', locality: '01', name: 'NORTH DAKOTA *' },
    { carrier: '15202', locality: '00', name: 'OHIO' },
    { carrier: '04312', locality: '00', name: 'OKLAHOMA' },
    { carrier: '02302', locality: '01', name: 'PORTLAND' },
    { carrier: '02302', locality: '99', name: 'REST OF OREGON' },
    { carrier: '12502', locality: '01', name: 'METROPOLITAN PHILADELPHIA ' },
    { carrier: '12502', locality: '99', name: 'REST OF PENNSYLVANIA' },
    { carrier: '09202', locality: '20', name: 'PUERTO RICO' },
    { carrier: '14412', locality: '01', name: 'RHODE ISLAND' },
    { carrier: '11202', locality: '01', name: 'SOUTH CAROLINA' },
    { carrier: '03402', locality: '02', name: 'SOUTH DAKOTA *' },
    { carrier: '10312', locality: '35', name: 'TENNESSEE' },
    { carrier: '04412', locality: '31', name: 'AUSTIN' },
    { carrier: '04412', locality: '20', name: 'BEAUMONT' },
    { carrier: '04412', locality: '09', name: 'BRAZORIA' },
    { carrier: '04412', locality: '11', name: 'DALLAS' },
    { carrier: '04412', locality: '28', name: 'FORT WORTH' },
    { carrier: '04412', locality: '15', name: 'GALVESTON' },
    { carrier: '04412', locality: '18', name: 'HOUSTON' },
    { carrier: '04412', locality: '99', name: 'REST OF TEXAS' },
    { carrier: '03502', locality: '09', name: 'UTAH' },
    { carrier: '14512', locality: '50', name: 'VERMONT' },
    { carrier: '11302', locality: '00', name: 'VIRGINIA' },
    { carrier: '09202', locality: '50', name: 'VIRGIN ISLANDS' },
    { carrier: '02402', locality: '02', name: 'SEATTLE ( KING CNTY' },
    { carrier: '02402', locality: '99', name: 'REST OF WASHINGTON' },
    { carrier: '11402', locality: '16', name: 'WEST VIRGINIA' },
    { carrier: '06302', locality: '00', name: 'WISCONSIN' },
    { carrier: '03602', locality: '21', name: 'WYOMING *' },
    { carrier: '10112', locality: '00', name: 'ALABAMA' },
    { carrier: '02102', locality: '01', name: 'ALASKA *' },
    { carrier: '03102', locality: '00', name: 'ARIZONA' },
    { carrier: '07102', locality: '13', name: 'ARKANSAS' },
    { carrier: '01112', locality: '54', name: 'BAKERSFIELD' },
    { carrier: '01112', locality: '55', name: 'CHICO ' },
    { carrier: '01182', locality: '71', name: 'EL CENTRO' },
    { carrier: '01112', locality: '56', name: 'FRESNO' },
    { carrier: '01112', locality: '57', name: 'HANFORD - CORCORAN' },
    { carrier: '01182', locality: '18', name: 'LOS ANGELES - LONG BEACH - ANAHEIM' },
    { carrier: '01182', locality: '26', name: 'LOS ANGELES - LONG BEACH - ANAHEIM' },
    { carrier: '01112', locality: '58', name: 'MADERA' },
    { carrier: '01112', locality: '59', name: 'MERCED' },
    { carrier: '01112', locality: '60', name: 'MODESTO' },
    { carrier: '01112', locality: '51', name: 'NAPA' },
    { carrier: '01112', locality: '07', name: 'SAN FRANCISCO - OAKLAND - HAYWARD' },
    { carrier: '01182', locality: '17', name: 'OXNARD - THOUSAND OAKS - VENTURA' },
    { carrier: '01112', locality: '61', name: 'REDDING' },
    { carrier: '01112', locality: '62', name: 'RIVERSIDE - SAN BERNARDINO - ONTAR' },
    { carrier: '01112', locality: '63', name: 'SACRAMENTO -- ROSEVILLE -- ARDEN - A' },
    { carrier: '01112', locality: '64', name: 'SALINAS' },
    { carrier: '01182', locality: '72', name: 'SAN DIEGO - CARLSBAD' },
    { carrier: '01112', locality: '05', name: 'SAN FRANCISCO - OAKLAND - HAYWARD ' },
    { carrier: '01112', locality: '52', name: 'SAN FRANCISCO - OAKLAND - HAYWARD ' },
    { carrier: '01112', locality: '65', name: 'SAN JOSE - SUNNYVALE - SANTA CLARA' },
    { carrier: '01182', locality: '73', name: 'SAN LUIS OBISPO - PASO ROBLES - AR' },
    { carrier: '01112', locality: '06', name: 'SAN FRANCISCO - OAKLAND - HAYWARD ' },
    { carrier: '01112', locality: '09', name: 'SAN JOSE - SUNNYVALE - SANTA CLARA' },
    { carrier: '01112', locality: '66', name: 'SANTA CRUZ - WATSONVILLE' },
    { carrier: '01182', locality: '74', name: 'SANTA MARIA - SANTA BARBARA' },
    { carrier: '01112', locality: '67', name: 'SANTA ROSA' },
    { carrier: '01112', locality: '68', name: 'STOCKTON - LODI' },
    { carrier: '01112', locality: '53', name: 'VALLEJO - FAIRFIELD' },
    { carrier: '01112', locality: '69', name: 'VISALIA - PORTERVILLE' },
    { carrier: '01112', locality: '70', name: 'YUBA CITY' },
    { carrier: '01112', locality: '75', name: 'REST OF CALIFORNIA' },
    { carrier: '04112', locality: '01', name: 'COLORADO' },
    { carrier: '13102', locality: '00', name: 'CONNECTICUT' },
    { carrier: '12202', locality: '01', name: 'DC + MD // VA SUBURBS' },
    { carrier: '12102', locality: '01', name: 'DELAWARE' },
    { carrier: '09102', locality: '03', name: 'FORT LAUDERDALE' },
    { carrier: '09102', locality: '04', name: 'MIAMI' },
    { carrier: '09102', locality: '99', name: 'REST OF FLORIDA' },
    { carrier: '10212', locality: '01', name: 'ATLANTA' },
    { carrier: '10212', locality: '99', name: 'REST OF GEORGIA' },
    { carrier: '01212', locality: '01', name: 'HAWAII , GUAM ' },
    { carrier: '02202', locality: '00', name: 'IDAHO' },
    { carrier: '06102', locality: '16', name: 'CHICAGO' },
    { carrier: '06102', locality: '12', name: 'EAST ST . LOUIS' },
    { carrier: '06102', locality: '15', name: 'SUBURBAN CHICAGO' },
    { carrier: '06102', locality: '99', name: 'REST OF ILLINOIS' },
    { carrier: '08102', locality: '00', name: 'INDIANA' },
    { carrier: '05102', locality: '00', name: 'IOWA' },
    { carrier: '05202', locality: '00', name: 'KANSAS' },
    { carrier: '15102', locality: '00', name: 'KENTUCKY' },
    { carrier: '07202', locality: '01', name: 'NEW ORLEANS' },
    { carrier: '07202', locality: '99', name: 'REST OF LOUISIANA' },
    { carrier: '14112', locality: '03', name: 'SOUTHERN MAINE' },
    { carrier: '14112', locality: '99', name: 'REST OF MAINE ' },
    { carrier: '12302', locality: '01', name: 'BALTIMORE // SURR . CNTYS' },
    { carrier: '12302', locality: '99', name: 'REST OF MARYLAND JNI' },
    { carrier: '14212', locality: '01', name: 'METROPOLITAN BOSTON' },
    { carrier: '10202', locality: '99', name: 'REST OF GEORGIA' },
    { carrier: '10302', locality: '35', name: 'TENNESSEE' },
    { carrier: '10202', locality: '01', name: 'ATLANTA , GA' },
    { carrier: '10102', locality: '00', name: 'ALABAMA' }
];
const ProviderAccount = ['0000-000 DEFAULT',
    '5700-000 CONTRACT PROVIDER',
    '5800-000 NO CONTRACT PROVIDER',
    '5800-600 MOU // ONE TIME AGREEMENTI',
    '5900-000 MOU AGREEMENT ONLY'];
const ProviderPaymentType = ['CAPITATED', 'FEE FOR SERVICE', 'MOU ONLY', 'OTHER', 'PARTIALLY CAP'];
const ProviderOrganizationType = ['ADDISTIONAL VENDOR TEST', 'PRIMARY', 'SECONDARY', 'THIRD', 'VENDHIST'];
const ProviderLetterMode = ['EMAIL', 'FAX', 'BATCH PRINT', 'NONE'];
const ProviderPracticeType = ['BILL - BILLING OFFICE',
    'BUS - BUSINESS OFFICE',
    'FAMP - FAMILY PRACTICE',
    'FQHC - FEDERALLY QUALIFIED HEALTH CLINIC',
    'GEA - GASTROENTERONASTOMOSIS',
    'GRP - GROUP',
    'H - HOME',
    'HDO - HEALTH DELIVERY ORGANIZATION',
    'M - MULTI SPECIALTY GROUP',
    'P - PARTNERSHIP',
    'P - PERSONAL',
    'PS - PROVIDER SERVICES',
    'SMG - SUTTER MEDICAL GROUP',
    'SOLO - SOLO PRACTICE',
    'SPEC - SPECIALIST',
    'SSG - SINGLE SPECIALTY GROUP',
    'UNKNOWN - UNKNOWN'];
const ProviderContractTemplate = ['100 MEDICARE MEDICAL RIVERSIDE [ 2018/01/01 ]',
    '100 % MCAL AND MCARE [1992/01/01 ]',
    '100 % MCARE 80 % MCAL 125 % COMM KERN [ 2017/01/01 ]',
    '100 % MEDI - CAL ALL LOB [ 2018/01/01 ]',
    '100 % MEDICARE & MEDI - CAL KERN [ 2017/01/01 ]',
    '100 % MEDICARE ALL LOB [ 2018/01/01 ]',
    '100 % MEDICARE LOS ANGELES [ 2018/01/01 ]',
    '80 % MEDICARE LOS ANGELES [ 2018/01/01 ]',
    '80 % OF MEDICARE ALL LOB [ 2018/01/01 ]',
    'ANESTHESIA $ 36 / UNIT [ 2018/01/01 ]',
    'CAPITATED NO CARVE OUTS [ 2015/01/01 ]',
    'CHILDRENS HOSPITAL OF LA - FACILITY [ 2017/12/01 ]',
    'Childrens Hospital of LA Professional [ 2017/12/01 ]',
    'CMG CAPPED CONTRACT [ 2018/01/01 ]',
    'CONCENTRA URGENT CARE [ 2018/10/01 ]',
    'KERN NON CONTRACTED [ 2017/01/01 ]',
    'LOS ANGELES NON CONTRACTED [ 2017/01/01 ]',
    'MCARE 80 % FOR MCAL , 110 % FOR MCARE AND 110 % FOR COMM [ 2018/01/01 ]',
    'MOU CONTRACT [ 2018/01/01 ]',
    'NON CONTRACTED [ 2018/01/01 PCP CAPITATION WITH CARVE OUT [ 2018/01/01 ]',
    'PENDING FEE SET 2019/01/01 ]',
    'PT Case Rate [ 2017/01/01 ]',
    'RIVERSIDE NON CONTRACTED [ 2017/01/01 ]',
    'Standard with Carve Out [ 2010/01/01 ]',
    'To be deleted by Edi support [ 2018/01/01 ]',
    'URGENT CARE CASE RATE [ 2018/01/01 ]'
];


/***/ })

}]);
//# sourceMappingURL=default~LazyComponents-non-credential-non-credential-module~LazyComponents-practionar-data-practiona~bc30a37e.js.map